apiVersion: v1
kind: Service
metadata:
  labels:
    run: sar2python
  name: sar2python-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: sar2python
  type: LoadBalancer
