apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: sar2python
  template: sar2python
message: |-
  The following service(s) have been created in your project: sar2python.
  For more information about using this template, including OpenShift considerations, see https://cloud.docker.com/repository/docker/cemtan/sar2python
metadata:
  annotations:
    description: SAR Database and Plotter application that serves static content. For more information about using this template, including OpenShift considerations, see https://cloud.docker.com/repository/docker/cemtan/sar2python
    iconClass: icon-apache
    openshift.io/display-name: SAR Database and Plotter
    openshift.io/documentation-url: https://cloud.docker.com/repository/docker/cemtan/sar2python
    openshift.io/long-description: This template defines resources needed to develop a static application served by SAR Database and Plotter, including a build configuration and application deployment configuration.
    openshift.io/provider-display-name: cemtan
    openshift.io/support-url: https://cloud.docker.com/repository/docker/cemtan/sar2python
    tags: sar2python
    template.openshift.io/bindable: "false"
  name: sar2python
  namespace: openshift
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: sar2python
  spec:
    ports:
    - name: web
      port: 5000
      targetPort: 5000
    selector:
      app: sar2python
- apiVersion: v1
  kind: Route
  metadata:
    name: sar2python
  spec:
    host: sar2python.localdomain
    to:
      kind: Service
      name: sar2python
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    label:
      app: sar2python
    name: sar2python
  spec:
    replicas: 1
    selector:
      app: sar2python
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: sar2python
        name: sar2python
      spec:
        containers:
        - env: []
          image: cemtan/sar2python:4.0.0
          name: sar2python-container
          ports:
          - containerPort: 5000
          resources:
            limits:
              memory: 512Mi
